### Should be fetched in 1 request
http://localhost:4041/passthrough/search_by_range?start_date=2019-01-01&end_date=2019-01-02

### More than 7 days - should be fetched in 2 requests
http://localhost:4041/passthrough/search_by_range?start_date=2019-01-01&end_date=2019-01-10

### details_of
http://localhost:4041/passthrough/details_of/2007822

### create favourite
POST http://localhost:4041/passthrough/favourites
Content-Type: application/json

{ "id": "2007827", "name": "7827 (2002 DB4)" }

### get all favourites
http://localhost:4041/passthrough/favourites
