CREATE DATABASE iridium;
CREATE USER iridium WITH PASSWORD 'iridium';
GRANT ALL PRIVILEGES ON DATABASE iridium TO iridium;

CREATE TABLE iridium.favourites
(
    id   INT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);
