### Good
http://localhost:4041/passthrough/search_by_range?start_date=2019-01-01&end_date=2019-01-02

### More than 7 days - should be fetched in 2 requests
http://localhost:4041/passthrough/search_by_range?start_date=2019-01-01&end_date=2019-01-10

### details_of
http://localhost:4041/passthrough/details_of/2007822

### Nasa
https://api.nasa.gov/neo/rest/v1/feed?start_date=2015-09-01&end_date=2015-09-08&api_key=DEMO_KEY

### Nasa sends back JSON in 400 response
https://api.nasa.gov/neo/rest/v1/feed?start_date=2015-09-01&end_date=2015-09-10&api_key=DEMO_KEY

### Nasa 301 redirect for http
http://api.nasa.gov/neo/rest/v1/neo/2007822?api_key=DEMO_KEY

### Nasa 200 for https
https://api.nasa.gov/neo/rest/v1/neo/2007822?api_key=DEMO_KEY
